version: "3"

services:
  mysqldb:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - mynetwork
  app:
    depends_on:
      - mysqldb
    image: imagebackend
    restart: always
    ports:
      - "8083:8082"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql:3306/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
